server:
  port: 8082

spring:
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    url: jdbc:h2:mem:clinic;DB_CLOSE_DELAY=-1
    username: jeremy
    password: jeremy
    h2:
      console:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

